// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYRgYh-GH0lmirSLiPNHBYU7ajlD1hKk0',
    appId: '1:921569007844:web:6df4abd6c109ec57bbb4f1',
    messagingSenderId: '921569007844',
    projectId: 'experience-5cde5',
    authDomain: 'experience-5cde5.firebaseapp.com',
    storageBucket: 'experience-5cde5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrREEsdGEHM2pM-blxxNr_K8qIjhNNs2g',
    appId: '1:921569007844:android:39f83ed45d34ad26bbb4f1',
    messagingSenderId: '921569007844',
    projectId: 'experience-5cde5',
    storageBucket: 'experience-5cde5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb00X2QY7hqlVhtkaY3rZ4juJm83JuYDQ',
    appId: '1:921569007844:ios:4eb5bc881ad52444bbb4f1',
    messagingSenderId: '921569007844',
    projectId: 'experience-5cde5',
    storageBucket: 'experience-5cde5.appspot.com',
    iosClientId: '921569007844-cl5igi5ccltdstfr25oq45nktbej704g.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication',
  );
}
